### ISSUE TITLE
Not saving edited files

### ISSUE THREAD

**Issue by aaaton** [coofercat/peeked#2]
I am having the issue that peeked is not saving any files. It says "saved", when clicking the icon but nothing changes. 

I am running locally on a macbook with the built in apachectl. 

There is a mention of _change permissions if needed_ in the readme. What is meant by this?

**Comment by coofercat** [comment]
Obviously, the UI shouldn't be saying "Saved" when it hasn't really done so. I'll see if there's anything I can do about that.

Your problem is (probably) ownership of files and processes. Usually, when you save files to your machine, they'll be owned by your user. However, Apache usually runs as a different user (either 'apache', 'httpd', 'webserver' or something else), so it can't overwrite your files.

You have a few choices:
- Change the permissions of your files to be world writable, or change them to be group writable by the Apache server process
- Change the ownership of your files to be the same as the user that runs Apache
- Change the user that Apache runs as (to be the same as the user that owns the files). Do some googling for the changes you'll need to make to the apache configs if you want to do this.
- Use PHP's built in web server (how to do this is in the Pico CMS docs). The PHP web server isn't a "full" server, so it's only good for personal use, but by the sounds of things that's enough for you. Since you'll run it as yourself, it'll have access to write to your files

**Comment by aaaton** [comment]
Thank you for your help! I tried changing the files in content to world writable, which helped. Would this be a safe solution if deployed on a real server, or do I need to change the owner of the files?

I mean the files aren't really accessible through the browser anyhow, without going through pico first...

**Comment by coofercat** [comment]
Personally, I don't like the idea of world-writable files, but a lot of people have them on their production systems and are perfectly fine. You may be able to tighten up a bit by adding your own user to the httpd group (and make them group writable) instead though.
